instance_type       = "t2.micro"
security_group_name = "launch-wizard-2"
security_group_id = "sg-08cd3ce3c53244046"
key_name            = "test_1"
region              = "eu-west-1"
repo_url            = "https://github.com/dberkerdem/MLOps-Article.git"
